MAKE = make
CXX = g++
CXXFLAGS = -Wall -Wunused-variable -Wmismatched-new-delete
FeaturizerCXXFLAGS = -std=c++11 -Wall -Wunused-variable -Wmismatched-new-delete
#OPTFLAGS = -O3
ifeq ($(UNAME_S),Darwin)
                OPTFLAGS = ""
endif
#DEBUG = -g
OTHERLIBS = ../
INCFLAGS = -I../lib -I$(OTHERLIBS)
LINKFLAGS = -L../lib -lmoletools 
BINDIR = ../bin
LIBEXT=a
